<div class="top-content">
    <div class="inner-bg">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 text">
                    <?php if (isset($successActivation) && $successActivation === true) { ?>
                        <h1><strong>Congratulation!</strong> Your Account is now Activated.</h1>
                    <?php } else { ?>
                        <h1><strong>404!</strong> Not Found</h1>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</div>