<div class="top-content">
    <div class="inner-bg">
        <div class="container">
            <div class="row">
                <div class="col-sm-7 text">
                    <h1><strong>Welcome!</strong> Registration Form</h1>
                </div>
                <div class="col-sm-5 form-box">
                    <div class="form-top">
                        <div class="form-top-left">
                            <h3>Sign up now</h3>
                            <p>Fill in the form below to get instant access:</p>
                        </div>
                        <div class="form-top-right">
                            <i class="fa fa-pencil"></i>
                        </div>
                    </div>
                    <div class="form-bottom">
                        <div class="alert alert-danger hide" id="error-message"></div>
                        <div class="alert alert-success hide" id="success-message"></div>
                        <form role="form" method="POST" enctype="multipart/form-data" id="registration-form" class="registration-form">
                            <div class="form-group">
                                <label class="sr-only" for="form-email">Email</label>
                                <input type="email" maxlength="255" name="form-email" placeholder="Email..." class="required form-email form-control" id="form-email">
                            </div>
                            <div class="form-group">
                                <label class="sr-only" for="form-password">Password</label>
                                <input type="password" maxlength="24" name="form-password" placeholder="Password..." class="required form-password form-control" id="form-password">
                            </div>
                            <div class="form-group">
                                <label class="sr-only" for="form-confirm-password">Confirm Password</label>
                                <input type="password" name="form-confirm-password" placeholder="Confirm Password..." class="required form-confirm-password form-control" id="form-confirm-password">
                            </div>
                            <div class="form-group">
                                <label class="sr-only" for="form-first-name">First name</label>
                                <input type="text" maxlength="30" name="form-first-name" placeholder="First Name..." class="required form-first-name form-control" id="form-first-name">
                            </div>
                            <div class="form-group">
                                <label class="sr-only" for="form-last-name">Last name</label>
                                <input type="text" maxlength="30" name="form-last-name" placeholder="Last Name..." class="required form-last-name form-control" id="form-last-name">
                            </div>
                            <div class="form-group">
                                <label class="sr-only" for="form-middle-name">Middle name</label>
                                <input type="text" maxlength="30" name="form-middle-name" placeholder="Middle Name..." class="form-middle-name form-control" id="form-middle-name">
                            </div>
                            <div class="form-group">
                                <div id="birthday" class="required"></div>
                            </div>
                            <div class="form-group">
                                <label class="sr-only" for="form-phone-number">Phone Number</label>
                                <input type="text" maxlength="11" name="form-phone-number[]" placeholder="Phone Number..." class="form-phone-number form-control" id="form-phone-number">
                            </div>
                            <div id="additional"></div>
                            <div class="form-group">
                                <label class="sr-only" for="form-profile-picture">Profile Picture</label>
                                <input type="file" name="form-profile-picture" placeholder="Profile Picture..." class="form-profile-picture form-control" id="form-profile-picture">
                            </div>
                            <div class="form-group">
                                <div class="radio-inline">
                                    <label for="form-gender-male" class="pull-right">Male</label>
                                    <input type="radio" name="form-gender" class="pull-left form-gender form-control-static" value="male" id="form-gender-male">
                                </div>
                                <div class="radio-inline">
                                    <label for="form-gender-female" class="pull-right">Female</label>
                                    <input type="radio" name="form-gender" class="pull-left form-gender form-control-static" value="male" id="form-gender-female">
                                </div>
                            </div>
                            <div class="form-group hide" id="loader">
                                <img src="<?=$html->getBaseUrl()?>/img/loader.gif"/>
                            </div>
                            <div class="form-group btnActions">
                                <button type="submit" class="btnActions btn">Sign me up!</button>
                                <a href="javascript:void(0);" id="add-phone-number" class="pull-right btnActions" title="Add Phone Number">Add Phone Number <i class="fa fa-plus"></i></a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>