<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Simple Registration Form</title>

    <!-- CSS -->
    <!--<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">-->
    <?=$html->includeCss('bootstrap.min.css');?>
    <?=$html->includeCss('font-awesome.min.css');?>
    <?=$html->includeCss('form-elements.css');?>
    <?=$html->includeCss('style.css');?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <?=$html->includeJs('head.min.js');?>

    <!-- Favicon and touch icons -->
    <link rel="shortcut icon" href="<?=$html->getBaseUrl();?>/ico/favicon.png">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?=$html->getBaseUrl();?>/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?=$html->getBaseUrl();?>/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?=$html->getBaseUrl();?>/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="<?=$html->getBaseUrl();?>/ico/apple-touch-icon-57-precomposed.png">

</head>

<body>
    <nav class="navbar navbar-inverse navbar-no-bg" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?=$html->getBaseUrl();?>">Registration Form</a>
            </div>
            <div class="collapse navbar-collapse" id="top-navbar-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>

                                <span class="li-social">
                                    <a href="http://www.facebook.com/ayhem30"><i class="fa fa-facebook"></i></a>
                                    <a href="mailto:ayhem30@gmail.com"><i class="fa fa-envelope"></i></a>
                                </span>
                    </li>
                </ul>
            </div>
        </div>
    </nav>